Fix async facade
riganti/infrastructure pull request #32
Opened 2018-08-01 04:48 UTC by Leeemons

2018-08-01 06:59 UTC, luboshl commented
@Leeemons, please add some description to this PR.

2018-08-01 07:36 UTC, luboshl requested changes
1. Add `CancellationToken` argument with the default value to all added async methods and use the value whenever possible.

2. `TemporalRelationshipCrudFacade` - this class was modified in PR #31, this PR does not fix the issues:
- `GetList` has not been fixed, still acts as a wrapper over async method
- `GetDetail` - DTTO
- `Save` - DTTO
- `Delete` - DTTO
- missing `GetRelationshipCollection` method
- `ValidateReadPermissions` - method was changed to async, but not renamed to `ValidateReadPermissionsAsync`. Missing sync version of the method.
- `HasReadPermissions` - DTTO
- `ValidateModifyPermissions` - DTTO
- `HasModifyPermissions` - DTTO

2018-08-01 07:36 UTC, luboshl commented on src/Infrastructure/Riganti.Utils.Infrastructure.Services/Facades/CrudFacadeBase.cs
> +        protected virtual Task ValidateReadPermissionsAsync(TEntity entity)
To be consistent (async method after sync), move this method after `ValidateReadPermissions(TEntity entity)`.

2018-08-01 07:36 UTC, luboshl commented on src/Infrastructure/Riganti.Utils.Infrastructure.Services/Facades/FilteredCrudFacadeBase.cs
> -                query.Filter = filter;
Why have you removed the filter?

2018-08-02 11:47 UTC, Leeemons commented
@luboshl I tried fixed all issues you reported

2018-08-02 19:27 UTC, luboshl reviewed
Please move the `CancellationToken` argument to be the last one and add the default value.

2018-08-02 19:29 UTC, luboshl requested changes
Please move the `CancellationToken` argument to be the last one and add the default value.

2018-08-02 20:09 UTC, luboshl requested changes
Still some (but small) issues.

2018-08-02 20:09 UTC, luboshl commented on src/Infrastructure/Riganti.Utils.Infrastructure.Services/Facades/TemporalRelationshipCrudFacade.cs
> +        protected virtual async Task ValidateReadPermissionsAsync(CancellationToken cancellationToken, TParentEntity entity)
Move this method just after its corresponding sync version to be together.

2018-08-02 20:09 UTC, luboshl commented on src/Infrastructure/Riganti.Utils.Infrastructure.Services/Facades/TemporalRelationshipCrudFacade.cs
> +        protected virtual Task<bool> HasReadPermissionsAsync(TParentEntity entity) => Task.FromResult(true);
Move this method just after its corresponding sync version to be together.

2018-08-02 20:09 UTC, luboshl commented on src/Infrastructure/Riganti.Utils.Infrastructure.Services/Facades/TemporalRelationshipCrudFacade.cs
> +        protected virtual async Task ValidateModifyPermissionsAsync(CancellationToken cancellationToken, TParentEntity entity)
Move this method just after its corresponding sync version to be together.

2018-08-02 20:09 UTC, luboshl commented on src/Infrastructure/Riganti.Utils.Infrastructure.Services/Facades/TemporalRelationshipCrudFacade.cs
> +        protected virtual Task<bool> HasModifyPermissionsAsync(TParentEntity entity) => Task.FromResult(true);
Move this method just after its corresponding sync version to be together.

2018-08-14 08:47 UTC, luboshl commented
As we discussed personally, `CancellationToken` really should be the last argument of the method. The situation is different in the Repository, because there are methods with the `params` argument and it has to be the last, there is no other option. In the future we could refactore these methods not to use `params` but `ICollection` as an argument for example, then the `CancellationToken` can also be the last one.

2018-08-17 07:44 UTC, luboshl approved these changes

2018-08-22 13:30 UTC, merged